version: 2.1

always-filter: &always-filter
  filters:
    branches:
      only: /.*/

main-filter: &main-filter
  filters:
    branches:
      only: main

orbs:
  node: circleci/node@5.2.0

executors:
  default:
    docker:
      - image: cimg/python:3.11-node
    resource_class: small

defaults: &defaults
  working_directory: ~/localstack-cicd
  executor: default

# job 1:
# 1. Install localstack
# job 2:
# 1. Start localstack
# 2. Deploy CDK with cdklocal
# 3. Test S3 with awslocal

jobs:
  install:
    <<: *defaults
    description: Install dependencies
    steps:
      - checkout
      - setup_remote_docker
      - node/install-packages
      - run:
          name: install LocalStack
          # npm with localstack has problems with cdklocal
          # should install globally rather than locally to fix
          # https://docs.localstack.cloud/user-guide/integrations/aws-cdk/#aws-cdk-cli-for-localstack
          command: |
            npm i -g aws-cdk-local aws-cdk
            pip3 install localstack awscli-local[ver1]
            docker pull localstack/localstack
      - persist_to_workspace:
          root: ~/localstack-cicd
          paths:
            - .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/localstack-cicd
      - run:
          name: deploy LocalStack
          command: |
            localstack start -d
            localstack wait -t 15
            cdklocal deploy
            awslocal s3api list-buckets

workflows:
  localstack-deploy:
    jobs:
      - install:
          <<: *always-filter
      - deploy:
          requires:
            - install
          <<: *always-filter
